- name: Configure User
  hosts: ericseyden.com
  remote_user: root
  tasks:
    - name: Add admins group
      ansible.builtin.group:
        name: admins
        state: present

    - name: Add webmasters group
      ansible.builtin.group:
        name: webmasters
        state: present

    - name: Add eseyden user
      ansible.builtin.user:
        name: eseyden
        groups: admins, wheel, webmasters

    - name: Set authorized key
      ansible.posix.authorized_key:
        user: eseyden
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub' ) }}"

    - name: Grant passwordless sudo access
      lineinfile:
        dest: /etc/sudoers
        line: "%admins ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s
        insertafter: EOF
        state: present

    - name: Install Required Packages
      package:
        name:
          - vim
          - tmux
          - git
        state: present
