- hosts: ericseyden.com
  become: true
  tasks:
    - name: Add webcontent user
      ansible.builtin.user:
        name: webcontent
        groups: webmasters

    - name: Generate Keypair
      openssh_keypair:
        path: /home/webcontent/.ssh/id_rsa
        owner: webcontent
        group: webcontent

    - name: Set authorized key
      ansible.posix.authorized_key:
        user: webcontent
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub' ) }}"

    - name: Create content directory
      file:
        path: /var/www/js/homepage-prod
        state: directory
        owner: webcontent
        group: webmasters
        mode: "774"

    - name: Install Required Packages
      package:
        name:
          - nodejs

    - name: Install PM2
      npm:
        name: pm2
        global: true
